### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by 0000ff** [Clicketyclick/ChangeScreenOrientation#2]
Hi, I was excited to find this script, as I have been looking for this functionality. Thanks. Just wondering if its possible to tweek the code to make the display go flipped landscape? Hard to find this command via Google...

**Comment by Clicketyclick** [comment]
Flip from default to 180 degree - and from 180 to normal
`
{
                    case NativeMethods.DMDO_DEFAULT:

                        //dm.dmDisplayOrientation = NativeMethods.DMDO_270;
                        //2016-10-25/EBP wrap counter clockwise
                        //dm.dmDisplayOrientation = NativeMethods.DMDO_90;
                        //2016-10-25/EBP Flip horizontal
                        dm.dmDisplayOrientation = NativeMethods.DMDO_180;
                        break;
                    case NativeMethods.DMDO_270:
                        dm.dmDisplayOrientation = NativeMethods.DMDO_180;
                        break;
                    case NativeMethods.DMDO_180:
                        //dm.dmDisplayOrientation = NativeMethods.DMDO_90;
                        // Back to normal
                        dm.dmDisplayOrientation = NativeMethods.DMDO_DEFAULT;
                        break;
                    case NativeMethods.DMDO_90:
                        dm.dmDisplayOrientation = NativeMethods.DMDO_DEFAULT;
                        break;
                    default:
                        // unknown orientation value
                        // add exception handling here
                        break;
                }
`

**Comment by 0000ff** [comment]
Thanks very much! I replace some lines in the command with this? As thanks, I can respond to your logo request.

**Comment by Clicketyclick** [comment]
Try the example. Should work with flipped screen

**Comment by 0000ff** [comment]
Thanks for the code. Only just now got around to trying it, unfortunately, the command doesn't flip, the screen just stays normal when executed.

**Comment by Clicketyclick** [comment]
Have you tried to call the original version of the script TWICE? That should do the trick
Will rotate the display clock wise to first 270 deg and then 180 deg
```
{
               case NativeMethods.DMDO_DEFAULT:
                    dm.dmDisplayOrientation = NativeMethods.DMDO_270;
                    break;
                case NativeMethods.DMDO_270:
                    dm.dmDisplayOrientation = NativeMethods.DMDO_180;
                    break;
                case NativeMethods.DMDO_180:
                    //dm.dmDisplayOrientation = NativeMethods.DMDO_90;
                    // Back to normal
                    dm.dmDisplayOrientation = NativeMethods.DMDO_DEFAULT;
                    break;
                case NativeMethods.DMDO_90:
                    dm.dmDisplayOrientation = NativeMethods.DMDO_DEFAULT;
                    break;
                default:
                    // unknown orientation value
                    // add exception handling here
                    break;
            }

```

**Comment by 0000ff** [comment]
Do you mean, run co.cmd twice? I've done that. Rotates to 90 degrees, then back again. Thanks for your response.

**Comment by 0000ff** [comment]
> Do you mean, run co.cmd twice? I've done that. Rotates to 90 degrees, then back again. Thanks for your response.

Just tried your latest code. It will flip to 90 degrees, then if I run it again, to 180. after that, running the script again does nothing.
