### ISSUE TITLE
Great code- is it possible to select which display is rotated?

### ISSUE THREAD

**Issue by Oliver-Johnson** [Clicketyclick/ChangeScreenOrientation#3]
I'm running a multi monitor setup which I usually run with either 4 or 5 displays. I would only like a specific one of these to rotate when I run this script.... Any good ideas how to do that?
Thanks in advance.

**Comment by Clicketyclick** [comment]
Sorry. Seems only to work with primary display.

**Comment by EarOfWheat** [comment]
Well, hope it's not too late. I use [NirCmd](https://nircmd.nirsoft.net/setprimarydisplay.html) for change the primary display temporary to do that.

The monitor number is the same as in Windows Settings -> System -> Display.

```bat
@REM I had add nircmd to environment variables
@echo off
nircmd setprimarydisplay 1
timeout /T 1
"D:\soft\ChangeOrientation.ps1"
nircmd setprimarydisplay 2
:end

```
