### ISSUE TITLE
Multi-Monitor

### ISSUE THREAD

**Issue by stephini** [Clicketyclick/ChangeScreenOrientation#4]
Hello, I was wondering what would need to be changed to allow this to affect specific monitors in a multi monitor setup and/or work from different default orientations with potentially different target orientations.

**Comment by Clicketyclick** [comment]
Suggestions are welcome - but I have no clue

**Comment by davidmakoto** [comment]
@stephini fwiw I hacked together a clunky way of changing specific monitor's orientations by changing the primary monitor before and after running the existing script via two calls to [MultiMonitorTool](https://www.nirsoft.net/utils/multi_monitor_tool.html). 

- Install [MultiMonitorTool](https://www.nirsoft.net/utils/multi_monitor_tool.html)
- Extract MultiMonitorTool.exe to where you will reference it (I put it in C:/Tools/)
- Edit ChangeScreenOrientation.ps1.cmd to swap primary displays before and after the program runs -- be mindful of which monitors line up with which numbers (available in display settings)
- For two monitors, where 1 is my primary and 2 is secondary, my edits look like this:
`C:/Tools/MultiMonitorTool.exe /SetPrimary 1
... <unchanged script>
C:/Tools/MultiMonitorTool.exe /SetPrimary 2
`

Make sure that this path matches where the .exe file was placed. 

Working so far for me, let me know if it gives you trouble!

**Comment by Clicketyclick** [comment]
Nice and simple

**Comment by juanakira** [comment]
> @stephini fwiw I hacked together a clunky way of changing specific monitor's orientations by changing the primary monitor before and after running the existing script via two calls to [MultiMonitorTool](https://www.nirsoft.net/utils/multi_monitor_tool.html).
> 
> * Install [MultiMonitorTool](https://www.nirsoft.net/utils/multi_monitor_tool.html)
> * Extract MultiMonitorTool.exe to where you will reference it (I put it in C:/Tools/)
> * Edit ChangeScreenOrientation.ps1.cmd to swap primary displays before and after the program runs -- be mindful of which monitors line up with which numbers (available in display settings)
> * For two monitors, where 1 is my primary and 2 is secondary, my edits look like this:
>   `C:/Tools/MultiMonitorTool.exe /SetPrimary 1 ... <unchanged script> C:/Tools/MultiMonitorTool.exe /SetPrimary 2 `
> 
> Make sure that this path matches where the .exe file was placed.
> 
> Working so far for me, let me know if it gives you trouble!

You're both legends, this works. Small thing but much better than dealing with Windows' way of doing it, with the "revert changes" pop up and all

**Comment by davidmakoto** [comment]
> You're both legends, this works. Small thing but much better than dealing with Windows' way of doing it, with the "revert changes" pop up and all

Thank you lol. Tell Microsoft to hire me

**Comment by Clicketyclick** [comment]
> > You're both legends, this works. Small thing but much better than dealing with Windows' way of doing it, with the "revert changes" pop up and all
> 
> Thank you lol. Tell Microsoft to hire me

Don't join The Dark Side :-E
