### ISSUE TITLE
Flip display

### ISSUE THREAD

**Issue by m0lmk** [Clicketyclick/ChangeScreenOrientation#5]
Is it possible to modify this so that it can flip the display? As in rotate it 180 degrees? I have an auxiliary monitor that is mounted upside down and would like to be able to move my windows desktop over to it when using a macbook on my main monitor. This script would be a great way to change the orientation without having to get into the display setting upside down! Thanks.

**Comment by Clicketyclick** [comment]
You could hard code this:

```
                    case NativeMethods.DMDO_DEFAULT:
                        //dm.dmDisplayOrientation = NativeMethods.DMDO_270;
                        //2016-10-25/EBP wrap counter clockwise
                        //dm.dmDisplayOrientation = NativeMethods.DMDO_90;
                        //2022-09-16/EBP Flip array
                        dm.dmDisplayOrientation = NativeMethods.DMDO_180;
```
